### ISSUE TITLE
Central Template Variables

### ISSUE THREAD

**Issue by cmcknz77** [andytruett/vscode-procurve-syntax#2]
Can you make it highlight (perhaps in yellow?) & allow collapse/expansion of Central Template Variables and conditional constructs? https://help.central.arubanetworks.com/latest/documentation/online_help/content/access-points/cfg/cfg-templates/prov_template_iap.htm?Highlight=variables

**Comment by andytruett** [comment]
I'll take a look and see what I can figure out!

Notes for my reference:
- https://code.visualstudio.com/docs/editor/codebasics#_folding
- https://code.visualstudio.com/api/language-extensions/language-configuration-guide

**Comment by andytruett** [comment]
Pushed out a new version with the changes, let me know if it satisfies what you're looking for!
